version: "3.8"
services:
  backend:
    image: docker-harbor.snt-online.at/tms/tms-backend:latest
    networks:
      - core-infra
    environment:
      - key=value # tms configuration goes here
  ai:
    image: docker-harbor.snt-online.at/tms/tms-ai
    networks:
      - core-infra
  frontend:
    image: docker-harbor.snt-online.at/tms/tms-frontend
    networks:
      - core-infra
    ports:
      - "4200:80"
