version: "3.8"
services:
  backend:
    build:
      context: ./backend/
    image: tms/backend
  frontend:
    build:
      context: ./frontend/
    depends_on:
      - "backend"
    ports:
      - 80:80
    image: tms/frontend-updated