spring:
  # Spring JDBC configuration
  datasource:
    # Let Spring Boot auto-configure an embedded HSQL database
    url:
  # Spring Data JPA configuration
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update