spring:
  # Spring JDBC configuration
  datasource:
    # Let Spring Boot auto-configure an embedded HSQL database
    url:
  # Spring Data JPA configuration
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

# App Properties
tms:
  jwt:
    secret: tmsSecret
    access-token-expiration: 900_000  # 15 minutes
    refresh-token-expiration: 86_400_000  # 24 hours
  mail:
    enabled: true
    receive:
      url: imaps://outlook.office365.com?authenticator=#customOAuth&unseen=true&delay=5000&mail.imaps.sasl.enable=true&mail.imaps.sasl.mechanisms=XOAUTH2&moveTo=tms
    oauth2:
      user: dominik.fluch@sntitsm.onmicrosoft.com
      password: 6s6amnwVtW3dhVC
      tenant: 6a43a57b-d4ab-4108-8849-2803ae065303
      clientId: ebfd3a25-8a34-4a6d-ac9c-29e6bc07f76c
      scope: https://outlook.office.com/IMAP.AccessAsUser.All
  classification:
    threshold: 100
    url: http://localhost:5000