database:
  kind: mysql
  url: jdbc:${database.kind}://localhost:3306/tms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  username: root
  password:

spring:
  # Spring JDBC configuration
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    initialization-mode: always

  # Spring Data JPA configuration
  jpa:
    database: ${database.kind}
    generate-ddl: false
    open-in-view: false
    hibernate:
      # To be updated in real production usage!
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comment: true
    #database-platform: org.hibernate.dialect.MySQL8Dialect