database:
  kind: mysql
  url: jdbc:${database.kind}://localhost:3306/tms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  username: root
  password:

spring:
  # Spring JDBC configuration
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    initialization-mode: always

  # Spring Data JPA configuration
  jpa:
    database: ${database.kind}
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comment: true
    #database-platform: org.hibernate.dialect.


# App Properties
tms:
  jwt:
    secret: ${tms.jwt.secret}
    access-token-expiration: ${tms.jwt.access-expiration}
    refresh-token-expiration: ${tms.jwt.refresh-secret}
  mail:
    enabled: ${tms.mail.enabled}
    receive:
      url: ${tms.mail.receive.url}
    oauth2:
      user: ${tms.mail.oauth2.user}
      password: ${tms.mail.oauth2.password}
      tenant: ${tms.mail.oauth2.tenant}
      clientId: ${tms.mail.oauth2.clientId}
      scope: ${tms.mail.oauth2.scope}
  classification:
    threshold: ${tms.classification.threshold}
    url: ${tms.classification.url}*/